mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
config:
  exporters:
    prometheus:
      endpoint: 0.0.0.0:8889
      send_timestamps: true
      metric_expiration: 180m
      resource_to_telemetry_conversion:
        enabled: true
  processors:
    batch:
      timeout: 5s
      send_batch_size: 100000
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [prometheus]
